$(document).ready(function() {
  // Slideshow on main page
  $('#slideshow').crossSlide({
    sleep: 5,
    fade: 1,
    shuffle: true
  }, [
    { src: '{{ site.github.url }}/images/slideshow/001.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/002.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/003.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/004.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/005.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/006.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/007.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/008.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/009.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/010.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/011.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/012.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/013.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/014.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/015.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/016.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/017.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/018.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/019.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/020.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/021.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/022.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/023.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/024.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/025.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/026.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/027.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/028.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/029.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/030.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/031.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/032.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/033.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/034.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/035.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/036.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/037.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/038.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/039.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/040.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/041.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/042.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/043.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/044.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/045.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/046.jpg' },
    { src: '{{ site.github.url }}/images/slideshow/047.jpg' }
  ]);
});
